#!/usr/bin/env python3
#coding: utf-8

import json, datetime, subprocess
import cgi

from settings.settings import TEMPERATURE_FILE

temperature = None

tfiles = subprocess.check_output(['cat',TEMPERATURE_FILE]).decode('utf-8')
now = datetime.datetime.now()
nowstr = now.isoformat().split(".")[0]
if tfiles.find("YES",30,60) != -1:
    idx = tfiles.find("t=",50,80)
    temperature = int(tfiles[idx+2:])/1000.0

output = {"time": nowstr, "temperature": temperature}

print("Content-Type: application/json")
print("")
print(json.dumps(output))
